# Ключевые слова для Канала 2: Автоматизация (n8n, GitHub, агенты, боты)

KEYWORDS_CHANNEL2 = [
    # Платформы автоматизации
    "n8n", "n8n.io", "n8n workflow", "n8n automation",
    "github", "github actions", "github workflow", "github automation",
    "zapier", "zapier automation", "zapier workflow",
    "make.com", "make automation", "integromat",
    "automate.io", "automate io",
    "power automate", "microsoft power automate", "flow power automate",
    "ifttt", "if this then that",
    "tray.io", "tray io",
    "workato", "workato automation",
    "uipath", "ui path",
    "automation anywhere",
    "node-red", "node red", "nodered",
    "huginn", "huginn automation",
    "airflow", "apache airflow",
    "prefect", "prefect automation",
    "dagster", "dagster automation",
    "luigi", "luigi workflow",
    "автоматизация процессов", "process automation", "workflow automation",
    "rpa", "robotic process automation", "роботизированная автоматизация процессов",
    
    # Агенты и автономные системы
    "ai agent", "ai агент", "ии агент", "автономный агент", "autonomous agent",
    "multi-agent", "мульти-агент", "multi agent", "мульти агент",
    "agent system", "система агентов", "агентная система",
    "agentic ai", "агентный ии", "агентный ai",
    "auto-gpt", "autogpt", "авто-gpt",
    "babyagi", "baby agi", "бэби-agi",
    "agentgpt", "agent gpt", "агент gpt",
    "gpt-engineer", "gpt engineer", "gpt инженер",
    "langchain", "ланг чейн", "lang chain",
    "langchain agents", "langchain агенты",
    "llm agents", "llm агенты", "агенты на llm",
    "ai workflow", "ai рабочий процесс", "ии рабочий процесс",
    "ai automation", "ai автоматизация", "ии автоматизация",
    "autonomous ai", "автономный ai", "автономный ии",
    "ai orchestration", "оркестрация ai", "оркестрация ии",
    "agent framework", "фреймворк агентов", "агентный фреймворк",
    "cognitive architecture", "когнитивная архитектура",
    "multi-modal agent", "мультимодальный агент", "multimodal agent",
    "agent memory", "память агента", "агентная память",
    "agent reasoning", "рассуждение агента", "агентное рассуждение",
    "agent planning", "планирование агента", "агентное планирование",
    "agent tools", "инструменты агента", "агентные инструменты",
    "agent marketplace", "маркетплейс агентов", "агентный маркетплейс",
    
    # Боты и чат-боты
    "chatbot", "чат-бот", "чатбот", "chat bot", "чат бот",
    "telegram bot", "телеграм бот", "telegram-bot", "телеграм-бот",
    "discord bot", "дискорд бот", "discord-bot", "дискорд-бот",
    "slack bot", "слак бот", "slack-bot", "слак-бот",
    "whatsapp bot", "вотсап бот", "whatsapp-bot", "вотсап-бот",
    "messenger bot", "мессенджер бот", "messenger-bot", "мессенджер-бот",
    "viber bot", "вайбер бот", "viber-bot", "вайбер-бот",
    "twitter bot", "твиттер бот", "twitter-bot", "твиттер-бот",
    "instagram bot", "инстаграм бот", "instagram-bot", "инстаграм-бот",
    "reddit bot", "реддит бот", "reddit-bot", "реддит-бот",
    "customer service bot", "бот поддержки клиентов", "бот обслуживания клиентов",
    "support bot", "бот поддержки", "support-bot",
    "sales bot", "бот продаж", "sales-bot",
    "marketing bot", "маркетинговый бот", "marketing-bot",
    "lead generation bot", "бот генерации лидов", "lead-generation-bot",
    "booking bot", "бот бронирования", "booking-bot",
    "scheduling bot", "бот планирования", "scheduling-bot",
    "notification bot", "бот уведомлений", "notification-bot",
    "reminder bot", "бот напоминаний", "reminder-bot",
    "survey bot", "бот опросов", "survey-bot",
    "quiz bot", "бот викторин", "quiz-bot",
    "game bot", "игровой бот", "game-bot",
    "entertainment bot", "развлекательный бот", "entertainment-bot",
    "news bot", "новостной бот", "news-bot",
    "weather bot", "погодный бот", "weather-bot",
    "finance bot", "финансовый бот", "finance-bot",
    "trading bot", "торговый бот", "trading-bot",
    "crypto bot", "крипто бот", "crypto-bot",
    "ai chatbot", "ии чатбот", "ai чатбот", "ии чат-бот", "ai чат-бот",
    "llm bot", "llm бот", "llm-bot",
    "gpt bot", "gpt бот", "gpt-bot",
    "bot framework", "фреймворк ботов", "bot-framework",
    "botpress", "ботпресс",
    "rasa", "раса", "rasa bot", "rasa бот",
    "dialogflow", "диалогфлоу",
    "botkit", "боткит",
    "microsoft bot framework", "майкрософт бот фреймворк",
    "создание ботов", "разработка ботов", "bot development", "bot creation",
    "конструктор ботов", "bot builder", "bot constructor",
    
    # Интеграции и API
    "api integration", "api интеграция", "интеграция api",
    "webhook", "вебхук", "web hook", "веб хук",
    "api gateway", "api шлюз", "шлюз api",
    "api management", "управление api", "менеджмент api",
    "api automation", "автоматизация api", "api автоматизация",
    "rest api", "рест api", "rest апи", "рест апи",
    "graphql", "графкл", "граф кл",
    "oauth", "oauth2", "оаут", "оаут2",
    "api key", "api ключ", "ключ api",
    "api token", "api токен", "токен api",
    "api documentation", "api документация", "документация api",
    "openapi", "опенапи", "open api", "опен апи",
    "swagger", "свагер",
    "api testing", "тестирование api", "api тестирование",
    "api monitoring", "мониторинг api", "api мониторинг",
    "api security", "безопасность api", "api безопасность",
    "api versioning", "версионирование api", "api версионирование",
    "api design", "дизайн api", "api дизайн",
    "api first", "api сначала", "сначала api",
    "microservices", "микросервисы", "micro services", "микро сервисы",
    "serverless", "бессерверный", "serverless functions", "бессерверные функции",
    "faas", "function as a service", "функция как сервис",
    
    # Монетизация ботов и автоматизации
    "bot monetization", "монетизация ботов", "монетизация бота",
    "automation monetization", "монетизация автоматизации",
    "bot subscription", "подписка на бота", "подписка бота",
    "automation subscription", "подписка на автоматизацию", "подписка автоматизации",
    "bot marketplace", "маркетплейс ботов", "маркетплейс бота",
    "automation marketplace", "маркетплейс автоматизации",
    "bot as a service", "бот как сервис", "baas",
    "automation as a service", "автоматизация как сервис", "aaas",
    "bot pricing", "цены на ботов", "цены бота",
    "automation pricing", "цены на автоматизацию", "цены автоматизации",
    "bot revenue", "доход от ботов", "доход бота",
    "automation revenue", "доход от автоматизации", "доход автоматизации",
    "bot business model", "бизнес-модель бота", "бизнес модель бота",
    "automation business model", "бизнес-модель автоматизации", "бизнес модель автоматизации",
    "bot roi", "рентабельность бота", "roi бота",
    "automation roi", "рентабельность автоматизации", "roi автоматизации",
    "bot saas", "бот saas", "бот как saas",
    "automation saas", "автоматизация saas", "автоматизация как saas",
    "bot licensing", "лицензирование бота", "лицензия бота",
    "automation licensing", "лицензирование автоматизации", "лицензия автоматизации",
    "bot white label", "бот white label", "бот вайт лейбл",
    "automation white label", "автоматизация white label", "автоматизация вайт лейбл",
    "bot reselling", "перепродажа бота", "реселлинг бота",
    "automation reselling", "перепродажа автоматизации", "реселлинг автоматизации",
    "bot affiliate", "партнерская программа бота", "аффилиат бота",
    "automation affiliate", "партнерская программа автоматизации", "аффилиат автоматизации",
    "gumroad bot", "gumroad бот", "бот gumroad",
    "gumroad automation", "gumroad автоматизация", "автоматизация gumroad",
    "sell bot", "продажа бота", "продать бота",
    "sell automation", "продажа автоматизации", "продать автоматизацию",
    "bot template", "шаблон бота", "темплейт бота",
    "automation template", "шаблон автоматизации", "темплейт автоматизации",
    "заработок на ботах", "заработок на автоматизации",
    "доход от ботов", "доход от автоматизации",
    "продажа решений автоматизации", "продажа ботов",
    
    # Русские ключевые слова
    "автоматизация процессов", "автоматизация бизнеса", "автоматизация задач",
    "создание ботов", "разработка ботов", "конструктор ботов",
    "интеграция сервисов", "интеграция приложений", "интеграция систем",
    "автоматизация рабочих процессов", "автоматизация рутины",
    "чат-бот для бизнеса", "бот для бизнеса", "бизнес-бот",
    "агенты искусственного интеллекта", "ии-агенты", "ai-агенты",
    "автономные системы", "автономные помощники",
    "монетизация автоматизации", "монетизация ботов", "монетизация агентов",
    "заработок на ботах", "заработок на автоматизации", "заработок на агентах"
]
