# Ключевые слова для Канала 1: Генерация контента (изображения, видео, озвучка, музыка)

KEYWORDS_CHANNEL1 = [
    # Генерация изображений - платформы
    "midjourney", "midjourney v6", "midjourney v7", "mj v6", "mj v7",
    "stable diffusion", "sdxl", "sd xl", "sd 3", "stable diffusion 3",
    "dall-e", "dall·e", "dalle", "dall-e 3", "dall·e 3", "dalle 3", "dall-e 4", "dall·e 4", "dalle 4",
    "leonardo ai", "leonardo.ai",
    "krea ai", "krea.ai",
    "playground ai", "playground.ai",
    "comfyui", "comfy ui",
    "invoke ai", "invoke.ai",
    "automatic1111", "automatic 1111", "a1111",
    "artbreeder",
    "flux ai", "flux.ai",
    "reve ai", "reve.ai",
    "firefly", "adobe firefly",
    "imagen", "google imagen",
    "ideogram", "ideogram ai",
    "getimg.ai",
    "civitai", "civit ai",
    "dreamstudio",
    "lexica", "lexica.art",
    "canva ai", "canva генерация",
    "генерация изображений", "image generation", "ai image", "ai art",
    
    # Генерация видео - платформы
    "sora", "openai sora", "sora video",
    "kling ai", "kling.ai", "kling video",
    "veo", "google veo", "deepmind veo", "google deepmind veo",
    "runway", "runway ml", "runway gen-2", "runway gen2", "runway gen 2",
    "pika", "pika labs", "pika.ai", "pika video",
    "dreamina", "capcut dreamina", "dreamina capcut",
    "kaiber", "kaiber ai", "kaiber.ai",
    "higgsfield", "higgsfield ai",
    "w.a.n.", "wan ai",
    "animatediff", "animate diff",
    "luma ai", "luma.ai", "luma video",
    "генерация видео", "video generation", "ai video", "ai animation",
    "text to video", "текст в видео", "image to video", "изображение в видео",
    
    # Озвучка и генерация голоса - платформы
    "elevenlabs", "eleven labs", "eleven.ai",
    "murf.ai", "murf ai",
    "play.ht", "play ht",
    "lovo.ai", "lovo ai",
    "speechki",
    "resemble ai", "resemble.ai",
    "ttsmaker", "tts maker",
    "coqui.ai", "coqui ai",
    "chatgpt read aloud", "read aloud",
    "mmaudio", "mm audio",
    "генерация голоса", "voice generation", "ai voice", "voice cloning", "клонирование голоса",
    "text to speech", "текст в речь", "tts", "озвучка", "озвучивание",
    
    # Генерация музыки и звуков - платформы
    "suno", "suno ai", "suno.ai",
    "udio", "udio ai", "udio.ai",
    "soundraw", "sound raw",
    "boomy", "boomy ai",
    "riffusion", "riffusion v2",
    "mmaudio", "mm audio",
    "генерация музыки", "music generation", "ai music", "ai audio",
    "text to music", "текст в музыку", "музыкальная генерация",
    
    # AI Fashion
    "ai fashion", "ai мода", "fashion ai", "мода ai", "ai одежда", "ai дизайн одежды",
    "ai clothing", "ai fashion design", "ai textile", "ai текстиль",
    "digital fashion", "цифровая мода", "виртуальная одежда", "virtual clothing",
    "fashion design ai", "дизайн одежды ai",
    
    # Конкурсы и челленджи
    "ai contest", "ai конкурс", "ai challenge", "ai челлендж",
    "midjourney contest", "midjourney challenge", "midjourney конкурс", "midjourney челлендж",
    "stable diffusion contest", "stable diffusion challenge",
    "kling challenge", "kling contest", "kling челлендж", "kling конкурс",
    "runway contest", "runway challenge", "runway конкурс", "runway челлендж",
    "ai art contest", "ai art challenge", "конкурс ai арт", "челлендж ai арт",
    "ai video contest", "ai video challenge", "конкурс ai видео", "челлендж ai видео",
    "prompt contest", "prompt challenge", "конкурс промптов", "челлендж промптов",
    
    # Монетизация и продажа контента
    "ai monetization", "монетизация ai", "monetize ai", "монетизировать ai",
    "sell ai art", "продажа ai арт", "продать ai арт", "selling ai art",
    "sell ai video", "продажа ai видео", "продать ai видео", "selling ai video",
    "ai stock", "ai сток", "stock ai", "сток ai",
    "ai marketplace", "ai маркетплейс",
    "nft ai", "ai nft", "нфт ai", "ai нфт",
    "ai print on demand", "ai pod", "ai принт",
    "ai licensing", "ai лицензирование",
    "ai royalties", "ai роялти",
    "gumroad ai", "ai gumroad",
    "etsy ai", "ai etsy",
    "ai commission", "ai комиссия", "комиссионные ai",
    "ai stock photo", "ai стоковое фото",
    "ai stock video", "ai стоковое видео",
    "ai stock music", "ai стоковая музыка",
    "ai stock audio", "ai стоковое аудио",
    "syky", "syky.com", "сайки",
    
    # Обновления и релизы
    "ai update", "ai обновление", "ai release", "ai релиз",
    "midjourney update", "обновление midjourney", "midjourney release", "релиз midjourney",
    "stable diffusion update", "обновление stable diffusion", "stable diffusion release", "релиз stable diffusion",
    "dall-e update", "обновление dall-e", "dall-e release", "релиз dall-e",
    "sora update", "обновление sora", "sora release", "релиз sora",
    "kling update", "обновление kling", "kling release", "релиз kling",
    "runway update", "обновление runway", "runway release", "релиз runway",
    "elevenlabs update", "обновление elevenlabs", "elevenlabs release", "релиз elevenlabs",
    "suno update", "обновление suno", "suno release", "релиз suno",
    
    # Русские ключевые слова
    "генеративный ai", "генеративный ии", "генеративная нейросеть",
    "нейросеть для изображений", "нейросеть для видео", "нейросеть для музыки", "нейросеть для голоса",
    "генерация контента", "создание контента нейросетью",
    "ai художник", "ии художник", "нейросеть художник",
    "ai видеограф", "ии видеограф", "нейросеть видеограф",
    "ai композитор", "ии композитор", "нейросеть композитор",
    "ai озвучка", "ии озвучка", "нейросеть озвучка",
    "продажа ai контента", "продажа ии контента", "продажа нейросетевого контента",
    "монетизация нейросети", "заработок на нейросети", "заработок на ai", "заработок на ии"
]
